export const CONTENTFUL_TOKEN_PRODUCTION = 'DZ3NCSif1UqjoiZFVz0gcGT3yTtnGnKFq646JV6FTxc';
export const CONTENTFUL_TOKEN_PREVIEW = 'K5r3zPcg2QG7M_Jp1pBPePJos--x3hVDK6WBKzBcvts';
export const CONTENTFUL_SPACE = 'buw9c3xj5wfc';
export const CONTENTFUL_ENV = 'master';

export default {
	CONTENTFUL_TOKEN_PRODUCTION,
	CONTENTFUL_TOKEN_PREVIEW,
	CONTENTFUL_SPACE,
	CONTENTFUL_ENV,
};
